#!/bin/bash

# echo "wmctrl -l | while read -r id rest; do" > /tmp/free-screen
# echo '    wmctrl -ic "$id"' >> /tmp/free-screen
# echo "done" >> /tmp/free-screen

echo "echo 'sleep 1 && sudo pkill x-terminal-emulator' > /tmp/eliminate-terminal" >> /tmp/free-screen
echo "echo 'sudo pkill xfce4-terminal' >> /tmp/eliminate-terminal" >> /tmp/free-screen
echo "echo 'sudo pkill xterm' >> /tmp/eliminate-terminal" >> /tmp/free-screen
echo "echo 'sudo pkill thunar' >> /tmp/eliminate-terminal" >> /tmp/free-screen
echo "echo 'sudo pkill pcmanfm' >> /tmp/eliminate-terminal" >> /tmp/free-screen
echo "echo 'sudo pkill thorium-browser' >> /tmp/eliminate-terminal" >> /tmp/free-screen
echo "echo 'sudo pkill brave-browser' >> /tmp/eliminate-terminal" >> /tmp/free-screen
echo "echo 'sudo pkill firefox-browser' >> /tmp/eliminate-terminal" >> /tmp/free-screen
echo "echo 'sudo pkill qemu' >> /tmp/eliminate-terminal" >> /tmp/free-screen
echo "echo 'sudo pkill tigervnc' >> /tmp/eliminate-terminal" >> /tmp/free-screen
echo "xterm -e 'xterm -e "nohup bash /tmp/eliminate-terminal"' &" >> /tmp/free-screen

# echo 'qdbus6 org.kde.kglobalaccel /component/kwin invokeShortcut "Show Desktop"' >> /tmp/free-screen

sudo cp /tmp/free-screen /bin/free-screen

sudo chmod +x /bin/free-screen

sudo chmod 777 /bin/free-screen

/bin/free-screen

source /bin/free-screen
