#!/bin/bash

sudo rm -f /tmp/free-screen /tmp/eliminate-terminal

echo "echo 'sleep 1 && sudo pkill x-terminal-emulator' > /tmp/eliminate-terminal" >> /tmp/free-screen
echo "echo 'sudo pkill xfce4-terminal' >> /tmp/eliminate-terminal" >> /tmp/free-screen
echo "echo 'sudo pkill xterm' >> /tmp/eliminate-terminal" >> /tmp/free-screen
echo "echo 'sudo pkill thunar' >> /tmp/eliminate-terminal" >> /tmp/free-screen
echo "echo 'sudo pkill pcmanfm' >> /tmp/eliminate-terminal" >> /tmp/free-screen
echo "echo 'sudo pkill thorium-browser' >> /tmp/eliminate-terminal" >> /tmp/free-screen
echo "echo 'sudo pkill brave-browser' >> /tmp/eliminate-terminal" >> /tmp/free-screen
echo "echo 'sudo pkill firefox-browser' >> /tmp/eliminate-terminal" >> /tmp/free-screen
echo "echo 'sudo pkill qemu' >> /tmp/eliminate-terminal" >> /tmp/free-screen
echo "echo 'sudo pkill tigervnc' >> /tmp/eliminate-terminal" >> /tmp/free-screen
echo "xterm -e 'xterm -e "nohup bash /tmp/eliminate-terminal"' &" >> /tmp/free-screen

# echo 'qdbus6 org.kde.kglobalaccel /component/kwin invokeShortcut "Show Desktop"' >> /tmp/free-screen

sudo cp /tmp/free-screen /bin/free-screen

sudo cp /bin/free-screen /bin/FREE

sudo chmod +x /bin/free-screen /bin/FREE

sudo chmod 777 /bin/free-screen /bin/FREE

clear
echo ''
echo 'active screen clear enabled' > /tmp/banner123
echo "run with 'free-screen' OR 'FREE'" >> /tmp/banner123
cat /tmp/banner123 | borderize | /usr/games/lolcat
echo ''
echo 'Hit enter to free-screen' | borderize | /usr/games/lolcat
echo ''
read p ''

source /bin/free-screen
