#!/bin/bash
sudo rm -f installer.sh
wget https://raw.githubusercontent.com/GlitchLinux/git-toolkit-gui/refs/heads/main/installer.sh
sudo chmod +x installer.sh
sudo bash installer.sh
sudo rm installer.sh
