#!/bin/bash
sudo touch /etc/apt/sources.list.d/kali.list
sudo echo "deb [trusted=yes] http://http.kali.org/kali kali-rolling main non-free contrib" >> /etc/apt/sources.list.d/kali.list
wget -qO - https://archive.kali.org/archive-key.asc | sudo apt-key add -
sudo apt update
sudo apt install -f kali-undercover
cd /etc/apt/sources.list.d/
sudo rm kali.list
