#!/bin/bash
cd /tmp
sudo wget https://github.com/goastian/midori-desktop/releases/download/v11.5.2/midori_11.5.2-1_amd64.deb
sudo dpkg -i midori_11.5.2-1_amd64.deb
sudo rm -f midori_11.5.2-1_amd64.deb
echo "MIDORI BROWSER INSTALLED"
exit
