#!/bin/bash

sudo apt update

sudo apt install qemu-system qemu-utils qemu-system-gui ovmf yad socat wget git orchis-gtk-theme -y

sudo mkdir -p /usr/share/QEMU-QuickBoot/

sudo curl -sL https://raw.githubusercontent.com/GlitchLinux/QEMU-QuickBoot/refs/heads/main/QEMU-QuickBoot.sh -o /usr/share/QEMU-QuickBoot/QEMU-QuickBoot.sh
sudo chmod +x /usr/share/QEMU-QuickBoot/QEMU-QuickBoot.sh

sudo curl -sL https://raw.githubusercontent.com/GlitchLinux/QEMU-QuickBoot/refs/heads/main/usb-hotplug.sh -o /usr/share/QEMU-QuickBoot/usb-hotplug.sh 
sudo chmod +x /usr/share/QEMU-QuickBoot/usb-hotplug.sh

sudo curl -sL https://raw.githubusercontent.com/GlitchLinux/QEMU-QuickBoot/refs/heads/main/Qemu-Quickboot.desktop -o /usr/share/applications/Qemu-Quickboot.desktop
sudo chmod +x /usr/share/applications/Qemu-Quickboot.desktop && sudo chmod 777 /usr/share/applications/Qemu-Quickboot.desktop

echo '#!/bin/bash' > /tmp/qboot
echo "sudo bash /usr/share/QEMU-QuickBoot/QEMU-QuickBoot.sh" >> /tmp/qboot
sudo cp /tmp/qboot /usr/local/bin/qboot
sudo chmod +x /usr/local/bin/qboot

cd /usr/share/QEMU-QuickBoot/
sudo rm *.png
sudo wget https://raw.githubusercontent.com/GlitchLinux/QEMU-QuickBoot/refs/heads/main/QEMU-QuickBoot.png && cd

echo ""
echo ""
echo "Qemu-Quickboot was successfully installed to system!"
echo "Application can be launched with 'qboot' in terminal"
echo "Or use the GUI desktop launcher in applications..."
echo " /usr/share/applications/Qemu-Quickboot.desktop"
echo ""
echo ""
