#!/bin/bash

sudo apt update

sudo apt install qemu-system qemu-utils qemu-system-gui ovmf yad socat wget git orchis-gtk-theme -y

sudo mkdir -p /usr/share/QEMU-QuickBoot/

sudo curl -sL https://raw.githubusercontent.com/GlitchLinux/QEMU-QuickBoot/refs/heads/main/QEMU-QuickBoot.sh -o /usr/share/QEMU-QuickBoot/QEMU-QuickBoot.sh
sudo chmod +x /usr/share/QEMU-QuickBoot/QEMU-QuickBoot.sh

sudo curl -sL https://raw.githubusercontent.com/GlitchLinux/QEMU-QuickBoot/refs/heads/main/usb-hotplug.sh -o /usr/share/QEMU-QuickBoot/usb-hotplug.sh 
sudo chmod +x /usr/share/QEMU-QuickBoot/usb-hotplug.sh

echo '#!/bin/bash' > /tmp/qboot
echo "sudo bash /usr/share/QEMU-QuickBoot/QEMU-QuickBoot.sh" >> /tmp/qboot
sudo cp /tmp/qboot /usr/local/bin/qboot
sudo chmod +x /usr/local/bin/qboot

cd /usr/share/QEMU-QuickBoot/
sudo wget https://raw.githubusercontent.com/GlitchLinux/QEMU-QuickBoot/refs/heads/main/QEMU-QuickBoot.png && cd

echo ""
echo "Qemu-Quickboot installed to system!"
echo "start in terminal with 'qboot'"
echo ""