#!/bin/bash
cd /tmp
wget https://github.com/Genymobile/scrcpy/releases/download/v4.1/scrcpy-linux-x86_64-v4.1.tar.gz
tar -xvf scrcpy-linux-x86_64-v4.1.tar.gz
sudo cp -r scrcpy-linux-x86_64-v4.1/ /home/x/
cd /home/x/scrcpy-linux-x86_64-v4.1
sudo chmod +x *
./scrcpy
