#!/bin/bash

# download and install squashfs-path-fix utility

cd /tmp && wget https://raw.githubusercontent.com/GlitchLinux/gLiTcH-Calamares/refs/heads/main/squashfs-symlink-fix
sudo cp squashfs-symlink-fix /usr/local/bin/squashfs-symlink-fix
sudo chmod +x /usr/local/bin/squashfs-symlink-fix
echo "squashfs-symlink-fix utility installed"

bash /usr/local/bin/squashfs-symlink-fix &
