#!/bin/bash

clear
echo "1. Glitch-Server" > /tmp/ssh-local
echo "2. Glitch-Server x11" >> /tmp/ssh-local
cat /tmp/ssh-local | borderize
echo " "

read -p "Select SSH Target [1-2]: " choice

case $choice in
    1)
        clear
	      ssh x@192.168.0.198
        ;;
    2)
        clear
        ssh -Y x@192.168.0.198 
        ;;
    *)
        clear && echo "Invalid Choice, Retry..." | borderize
        sleep 2
        bash /bin/ssh-localhost
        ;;
esac
