sudo rm /MiniDeb.tar && sudo tar --numeric-owner --one-file-system \
  --exclude=/proc \
  --exclude=/sys \
  --exclude=/dev \
  --exclude=/run \
  --exclude=/tmp \
  --exclude=/mnt \
  --exclude=/media \
  --exclude=/lost+found \
  --exclude=/swapfile \
  --exclude=/var/cache/apt/archives \
  -C / -c . > /MiniDeb.tar
